services:
  - type: web
    name: sentiment-aware-translation
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 2000
